/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState } from 'react';

const LangContext = createContext(null);

export const translations = {
  en: {
    siteName: 'MLA Public Grievance Portal',
    mlaName: 'MLA Rahul Subhash Kul',
    constituency: 'Daund, Maharashtra',
    welcome: 'Welcome to the MLA Grievance Redressal Portal',
    welcomeSub: 'Your voice matters. Submit your complaints and track their resolution.',
    fileComplaint: 'File a Complaint',
    trackComplaint: 'Track Complaint',
    home: 'Home', complaints: 'Complaints',
    track: 'Track', admin: 'Admin',
    totalComplaints: 'Total Complaints', pending: 'Pending',
    inProgress: 'In Progress', resolved: 'Resolved',
    name: 'Full Name', mobile: 'Mobile Number', village: 'Village',
    taluka: 'Taluka', department: 'Department', description: 'Complaint Description',
    photo: 'Photo (Optional)',
    submit: 'Submit Complaint',
    complaintId: 'Complaint ID', status: 'Status', remarks: 'Admin Remarks',
    date: 'Date', actions: 'Actions', search: 'Search',
    filterTaluka: 'Filter by Taluka', filterDept: 'Filter by Department',
    exportCSV: 'Export CSV', adminLogin: 'Admin Login',
    password: 'Password', login: 'Login', logout: 'Logout',
    searchPlaceholder: 'Search complaints (ID, Name, Mobile, Village, Description)...',
    noComplaintsFound: 'No complaints found matching your criteria.',
    refresh: 'Refresh',
    prev: 'Prev',
    next: 'Next',
    allTalukas: 'All Talukas',
    allDepartments: 'All Departments',
    allStatuses: 'All Statuses',
    dashboard: 'Dashboard', manageComplaints: 'Manage Complaints',
    analytics: 'Analytics', users: 'Users Management',
    settings: 'Settings',
    statsOverview: 'Overview of all grievances',
    totalComplaintsLabel: 'Total Complaints',
    resolvedLabel: 'Resolved',
    inProgressLabel: 'In Progress',
    resolutionRate: 'Resolution Rate',
    pendingRate: 'Pending Rate',
    rejected: 'Rejected',
    departmentsTitle: 'Departments',
    pendingLabel: 'pending',
    quickActions: 'Quick Actions',
    viewAllComplaints: 'View All Complaints',
    exportData: 'Export Data',
    analyticsTitle: 'Analytics Dashboard',
    resolutionInsights: 'Visual insights into grievance data',
    complaintsByDept: 'Complaints by Department',
    complaintsByTaluka: 'Complaints by Taluka',
    monthlyTrend: 'Monthly Complaint Trend',
    createUserInfo: 'Create New User',
    allUsers: 'All Users',
    createUser: 'Create User',
    saveChanges: 'Save Changes',
    active: 'Active',
    inactive: 'Inactive',
    profileUpdate: 'Update Profile',
    successProfileUpdate: 'Profile updated successfully!',
    privacyError: 'Privacy restricted: You can only search your own mobile number.',
    mobileOwnershipError: 'You must be logged in to search by mobile number.',
    changePassword: 'Change Password (Optional)',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    passwordPlaceholder: 'Leave blank to keep unchanged',
    minChars: 'Min 6 characters',
    roles: {
      super_admin: 'Super Admin',
      taluka_coordinator: 'Taluka Coordinator',
      data_entry_operator: 'Data Entry Operator',
      citizen: 'Citizen'
    },
    noComplaintsTitle: 'No complaints found',
    noComplaintsSub: 'No complaints found for this ID or mobile number.',
    complaintsFoundLabel: 'complaint(s) found',
    filedOn: 'Filed On',
    resolvedOn: 'Resolved On',
    submitted: 'Submitted',
    adminRemarks: 'Admin Remarks',
    adminReplyPhotos: 'Admin Reply Photos',
    citizenReplyPhotos: 'My Reply Photos',
    initialPhoto: 'Initial Uploaded Photo',
    replyMorePhotos: 'Reply / Upload More Photos',
    replyLimitInfo: 'You can upload up to {n} more photos',
    dragDropHint: 'Drag & drop or click to upload',
    fileLimitInfo: 'JPG, PNG, PDF up to 5MB',
    fileLimitInfoSmall: 'JPG, PNG, PDF up to 5MB',
    sendingReply: 'Uploading...',
    sendReply: 'Send Reply',
    fileSelected: '{n} file(s) selected',
    fileSizeError: 'Some files were ignored because they exceed the 5MB limit.',
    atLeastOnePhotoError: 'Please select at least one photo to reply.',
    replySuccess: 'Reply submitted successfully!',
    loginRequired: 'Login Required',
    loginRequiredSub: 'Please log in to register a complaint.',
    goToLogin: 'Go to Login',
    submitComplaintTitle: 'Submit Your Complaint',
    submitComplaintSub: 'Register your issue here',
    namePlaceholder: 'Enter full name',
    mobilePlaceholder: '10-digit mobile number',
    mobileLocked: 'Mobile locked to your login account',
    searchHint: 'e.g. GRV-ABC123-XY or 9876543210',
    villagePlaceholder: 'Enter your village name',
    selectTaluka: '— Select Taluka —',
    descriptionPlaceholder: 'Describe your complaint in detail...',
    submitting: 'Submitting...',
    genuineComplaintWarning: 'By submitting, you agree that this is a genuine complaint.',
    updateSuccess: 'Updated successfully!',
    noChangesError: 'No changes to save.',
    updateError: 'Update failed. Please try again.',
    deleteConfirm: 'Are you sure you want to delete this user?',
    viewMyComplaints: 'View My Complaints',
    successSubmit: 'Complaint submitted successfully!',
    close: 'Close',
    viewDetails: 'View Details',
    details: 'Details',
    citizenUploaded: 'Citizen Uploaded',
    items: 'items',
    total: 'total',
    page: 'Page',
    whatsapp: 'WhatsApp Us',
    darkMode: 'Dark Mode',
    language: 'मराठी',
    extraFeaturesTitle: 'Extra Features',
    extraFeaturesSub: 'Smart services for digital empowerment',
    aiAssistantTitle: '24/7 AI Assistant',
    aiAssistantDesc: 'Register complaints and get project information instantly.',
    aiStatus: 'ONLINE & READY',
    aiGreeting: 'Hello! I am your Daund Digital Assistant. How can I help you today?',
    aiUpdateMsg: '🇮🇳 अपडेट: Zilla Parishad School Renovation प्रकल्पाचे काम सध्या जोरात सुरू आहे! Modernizing 10 rural schools with digital labs.. आम्ही दौंडच्या प्रगतीसाठी कटिबद्ध आहोत.',
    aiPlaceholder: 'Type or use Mic...',
    aiAskComplaint: 'How to file a complaint?',
    aiAskProjects: 'What are the recent projects?',
    aiAskEmergency: 'Show emergency contacts',
    transparencySub: 'Tracking public funds and progress',
    mlaFundTrackerTitle: 'MLA Fund Expenditure Tracker (2024-25)',
    roads: 'Roads',
    water: 'Water',
    education: 'Education',
    health: 'Health',
    crore: 'Cr',
    projects: 'Projects',
    addProject: 'Add Project',
    editProject: 'Edit Project',
    projectTitle: 'Project Title',
    projectDesc: 'Description',
    estimatedBudget: 'Estimated Budget',
    actualSpent: 'Actual Spent',
    complete: 'Complete',
    underProcess: 'Under Process',
    incomplete: 'Incomplete',
    totalBudget: 'Total Budget',
    totalSpent: 'Total Spent',
    totalProjects: 'Total Projects',
    allProjects: 'All Projects',
    projectAdded: 'Project added successfully',
    projectUpdated: 'Project updated successfully',
    projectDeleted: 'Project deleted successfully',
    expectedCompletion: 'Expected Completion',
    completionDate: 'Completion Date',
    emergencyCall: 'Call Now',
    police: 'Police Station',
    ambulance: 'Ambulance / Hospital',
    fire: 'Fire Brigade',
    electricity: 'Electricity Board',
    tehsildar: 'Tehsildar Office',
    comingSoon: 'Coming Soon',
    citizenRegistration: 'Citizen Registration',
    createAccountSub: 'Create an account to file complaints',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    selectTalukaOptional: 'Taluka (Optional)',
    register: 'Register',
    registering: 'Registering...',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    citizenLogin: 'Citizen Login',
    accessComplaintsSub: 'Access your complaints',
    loggingIn: 'Logging in...',
    dontHaveAccount: "Don't have an account?",
    registerHere: 'Register here',
    authPersonnelOnly: 'Authorized Personnel Only',
    marathiAuthSub: 'केवळ अधिकृत कर्मचार्‍यांसाठी',
    aiMessageRBot: 'Message RBot...',
    aiRBotPersona: 'RBot • AI Agent • Now',
    aiMistakesDisclaimer: 'RBot can make mistakes. Verify important info.',
    aiOnlineReady: 'ONLINE & READY',
    aiTeamHelp: 'The team can also help',
    complaintIdOrMobile: 'Complaint ID or Mobile Number',
    minSixChars: 'Minimum 6 characters',
    road: 'Road',
    waterDept: 'Water',
    electricityDept: 'Electricity',
    revenue: 'Revenue',
    police: 'Police',
    health: 'Health',
    education: 'Education',
    agri: 'Agriculture',
    other: 'Other',
    maxChars: 'max 500 chars',
    photoOptional: 'Photo (Optional)',
    searching: 'Searching...',
    pendingStatus: 'Pending',
    inProgressStatus: 'In Progress',
    resolvedStatus: 'Resolved',
    stepText: 'STEP',
    officialPortal: 'Official Portal',
    digitalIndia: 'Digital India',
    onlineSupportBadge: '24/7 ONLINE SUPPORT',
    quickLinks: 'Quick Links',
    contact: 'Contact',
    followUs: 'Follow Us',
    rbotGreeting: 'Hello! I am your Digital Seva Assistant. How can I help you today? 🙏',
    chatWithSupport: 'Chat with RBot Support',
    rbotHome: 'Home',
    rbotMessages: 'Messages',
    rbotHelp: 'Help',
    adminLogoutNotice: 'You were logged out. Admins cannot use the Citizen portal.',
    citizenLogoutNotice: 'You were logged out. This portal is for admin staff only.',
    emergencyServices: 'Emergency Services',
    publicUtilities: 'Public Utilities',
    importantNote: 'Important Note',
    emergencyDisclaimer: 'These numbers are for emergency and official use only. Please use them responsibly to ensure help reaches those in need promptly.',
    officeDaund: 'Office · Daund',
    priorityMsg: 'Solving your problems is our priority',
    joinThousands: 'Join thousands of citizens in Daund who are getting their grievances resolved swiftly and transparently through our official portal.',
    citizensRegistered: 'citizens already registered',
    mlaTitle: 'MLA - Daund Constituency',
    assemblyName: 'Maharashtra Legislative Assembly',
    responseRate: 'Response Rate',
    howItWorksTitle: 'How It Works',
    howItWorksSub: 'Simple 3-step process to resolve your grievance',
    step1Title: 'File Complaint',
    step1Desc: 'Fill in the complaint form with your details and description.',
    step2Title: 'Get Complaint ID',
    step2Desc: 'Receive a unique Complaint ID for tracking your complaint.',
    step3Title: 'Track Resolution',
    step3Desc: 'Track the status and get notified when resolved.',
    complaintCategories: 'Complaint Categories',
    categoriesSub: 'We handle grievances across all government departments',
    liveUpdates: 'Live Updates Active',
    fileNow: 'File Now',
    trackStatus: 'Track Status',
    recordingNotice: 'This chat session is recorded to ensure service quality.',
    helped: 'That helped 👍',
    showMore: 'Show me more 👀',
    talkPerson: 'Talk to a person 👤',
    replyNeeded: 'Reply Needed',
    adminRemarkPrompt: 'Admin has left a remark. You can upload more photos if requested.',
    complaintGuide: 'Complaint Guide',
    statusGuide: 'Status Guide',
    automaticSyncNotice: 'All complaints filed with your mobile number {n} are automatically shown above.',
    loginBtn: 'Login',
    signupBtn: 'Sign Up',
    or: 'or',
    daundVikasMitra: 'Daund Vikas Mitra',
    helloHowHelp: 'Hello There! How can we help?',
    sendMessageSub: 'Send us a message',
    chatSupportSub: 'Chat with RBot Support',
    suggestedArticles: 'Suggested Articles',
    searchHelpPlaceholder: 'Search for help',
    securityFooter: '🔐 Secured by JWT. Authorized personnel only.',
    committedToResolving: 'Committed to resolving public grievances swiftly and transparently.',
    allRightsReserved: 'All Rights Reserved.',
    adminPortalOnly: 'This portal is for admin staff only.',
    enterPassword: 'Enter your password',
    eGovernance: 'E-Governance',
    permHubTitle: 'Allow System Permissions',
    permHubSub: 'For a better experience, please allow the following permissions.',
    permLocation: 'Location (To find nearby development projects)',
    permCamera: 'Camera (To upload photos of grievances)',
    permMic: 'Microphone (For voice chat with AI)',
    allowAll: 'Allow All Permissions',
    maybeLater: 'Maybe Later',
    allPermsGranted: 'All permissions granted successfully!',
    permsDeniedMsg: 'Some permissions were denied. Please enable them in browser settings.',
  },
  mr: {
    siteName: 'आमदार सार्वजनिक तक्रार निवारण पोर्टल',
    mlaName: 'आमदार राहुल सुभाष कुल',
    constituency: 'दौंड, महाराष्ट्र',
    welcome: 'आमदार तक्रार निवारण पोर्टलमध्ये आपले स्वागत आहे',
    welcomeSub: 'आपला आवाज महत्त्वाचा आहे. आपल्या तक्रारी सादर करा आणि त्यांचे निराकरण ट्रॅक करा.',
    fileComplaint: 'तक्रार नोंदवा',
    trackComplaint: 'तक्रार ट्रॅक करा',
    home: 'मुख्यपृष्ठ', complaints: 'तक्रारी',
    track: 'ट्रॅक', admin: 'प्रशासक',
    totalComplaints: 'एकूण तक्रारी', pending: 'प्रलंबित',
    inProgress: 'प्रक्रियेत', resolved: 'निराकृत',
    name: 'पूर्ण नाव', mobile: 'मोबाइल नंबर', village: 'गाव',
    taluka: 'तालुका', department: 'विभाग', description: 'तक्रार तपशील',
    photo: 'फोटो (पर्यायी)',
    submit: 'तक्रार सादर करा',
    complaintId: 'तक्रार क्रमांक', status: 'स्थिती', remarks: 'प्रशासक टिप्पणी',
    date: 'तारीख', actions: 'कृती', search: 'शोधा',
    filterTaluka: 'तालुकानुसार फिल्टर', filterDept: 'विभागानुसार फिल्टर',
    exportCSV: 'CSV निर्यात', adminLogin: 'प्रशासक लॉगिन',
    password: 'पासवर्ड', login: 'लॉगिन', logout: 'लॉगआउट',
    searchPlaceholder: 'तक्रारी शोधा (नंबर, नाव, मोबाइल, गाव, तपशील)...',
    noComplaintsFound: 'आपल्या निकषांशी जुळणारी एकही तक्रार आढळली नाही.',
    refresh: 'रिफ्रेश',
    prev: 'मागे',
    next: 'पुढे',
    allTalukas: 'सर्व तालुके',
    allDepartments: 'सर्व विभाग',
    allStatuses: 'सर्व स्थिती',
    dashboard: 'डॅशबोर्ड', manageComplaints: 'तक्रारी व्यवस्थापन',
    analytics: 'विश्लेषण', users: 'वापरकर्ते व्यवस्थापन',
    settings: 'सेटिंग्ज',
    statsOverview: 'तक्रारींचा आढावा',
    totalComplaintsLabel: 'एकूण तक्रारी',
    resolvedLabel: 'निराकृत',
    inProgressLabel: 'प्रक्रियेत',
    resolutionRate: 'निराकरण दर',
    pendingRate: 'प्रलंबित दर',
    rejected: 'नाकारलेले',
    departmentsTitle: 'विभाग',
    pendingLabel: 'प्रलंबित',
    quickActions: 'त्वरित कृती',
    viewAllComplaints: 'सर्व तक्रारी पहा',
    exportData: 'डेटा निर्यात करा',
    analyticsTitle: 'विश्लेषण डॅशबोर्ड',
    resolutionInsights: 'तक्रार निवारण अंतर्दृष्टी',
    complaintsByDept: 'विभागांनुसार तक्रारी',
    complaintsByTaluka: 'तालुक्यांनुसार तक्रारी',
    monthlyTrend: 'मासिक तक्रार कल',
    createUserInfo: 'नवीन वापरकर्ता तयार करा',
    allUsers: 'सर्व वापरकर्ते',
    createUser: 'वापरकर्ता तयार करा',
    saveChanges: 'बदल जतन करा',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    profileUpdate: 'प्रोफाइल अपडेट करा',
    successProfileUpdate: 'प्रोफाइल यशस्वीरित्या अपडेट केली!',
    privacyError: 'गोपनीयता प्रतिबंधित: आपण फक्त आपला स्वतःचा मोबाइल नंबर शोधू शकता.',
    mobileOwnershipError: 'मोबाइल नंबरद्वारे शोधण्यासाठी कृपया लॉग इन करा.',
    changePassword: 'पासवर्ड बदला (पर्यायी)',
    currentPassword: 'चालू पासवर्ड',
    newPassword: 'नवीन पासवर्ड',
    passwordPlaceholder: 'बदल न करण्यासाठी रिक्त ठेवा',
    minChars: 'किमान ६ वर्ण',
    roles: {
      super_admin: 'सुपर ॲडमिन',
      taluka_coordinator: 'तालुका समन्वयक',
      data_entry_operator: 'डेटा एंट्री ऑपरेटर',
      citizen: 'नागरिक'
    },
    noComplaintsTitle: 'तक्रार आढळली नाही',
    noComplaintsSub: 'या आयडी किंवा मोबाइल नंबरसाठी कोणतीही तक्रार आढळली नाही.',
    complaintsFoundLabel: 'तक्रारी आढळल्या',
    filedOn: 'दाखल तारीख',
    resolvedOn: 'निकाली तारीख',
    submitted: 'सादर केली',
    adminRemarks: 'प्रशासकीय शेरा',
    adminReplyPhotos: 'प्रशासक फोटो',
    citizenReplyPhotos: 'माझे फोटो',
    initialPhoto: 'सुरुवातीचा फोटो',
    replyMorePhotos: 'उत्तर द्या / अधिक फोटो अपलोड करा',
    replyLimitInfo: 'तुम्ही आणखी {n} फोटो अपलोड करू शकता',
    dragDropHint: 'फोटो येथे ओढा किंवा अपलोड करण्यासाठी क्लिक करा',
    fileLimitInfo: 'JPG, PNG, PDF ५MB पर्यंत',
    fileLimitInfoSmall: 'JPG, PNG, PDF ५MB पर्यंत',
    sendingReply: 'अपलोड होत आहे...',
    sendReply: 'उत्तर पाठवा',
    fileSelected: '{n} फाइल निवडली',
    fileSizeError: 'काही फाइल्स ५MB पेक्षा जास्त असल्यामुळे वगळल्या गेल्या.',
    atLeastOnePhotoError: 'कृपया प्रतिसादासाठी किमान एक फोटो निवडा.',
    replySuccess: 'उत्तर यशस्वीरित्या पाठवले!',
    loginRequired: 'लॉगिन आवश्यक',
    loginRequiredSub: 'तक्रार नोंदवण्यासाठी कृपया आधी लॉग इन करा.',
    goToLogin: 'लॉगिन करा',
    submitComplaintTitle: 'तुमची तक्रार सादर करा',
    submitComplaintSub: 'तुमची समस्या येथे नोंदवा',
    namePlaceholder: 'पूर्ण नाव टाका',
    mobilePlaceholder: '१०-अंकी मोबाइल नंबर',
    mobileLocked: 'मोबाइल नंबर बदलता येणार नाही',
    searchHint: 'उदा. GRV-ABC123-XY किंवा 9876543210',
    villagePlaceholder: 'गावाचे नाव टाका',
    selectTaluka: '— तालुका निवडा —',
    descriptionPlaceholder: 'तक्रारीचा सविस्तर तपशील द्या...',
    submitting: 'सादर होत आहे...',
    genuineComplaintWarning: 'सादर करून, आपण सहमत आहात की ही खरी तक्रार आहे.',
    updateSuccess: 'यशस्वीरित्या अपडेट केले!',
    noChangesError: 'बदल करण्यासाठी काहीही नाही.',
    updateError: 'अपडेट अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    deleteConfirm: 'आपल्याला खात्री आहे की आपण हा वापरकर्ता हटवू इच्छिता?',
    viewMyComplaints: 'माझ्या तक्रारी पहा',
    successSubmit: 'तक्रार यशस्वीरित्या नोंदवली गेली!',
    close: 'बंद करा',
    viewDetails: 'तपशील पहा',
    details: 'तपशील',
    citizenUploaded: 'नागरिकाने अपलोड केलेले',
    items: 'तक्रारी',
    total: 'एकूण',
    page: 'पृष्ठ',
    whatsapp: 'व्हाट्सअॅप करा',
    darkMode: 'डार्क मोड',
    language: 'English',
    extraFeaturesTitle: 'वैशिष्ट्यपूर्ण विभाग',
    extraFeaturesSub: 'डिजिटल सक्षमीकरणासाठी स्मार्ट सेवा',
    aiAssistantTitle: '24/7 AI सहाय्यक',
    aiAssistantDesc: 'तक्रार नोंदणी आणि प्रकल्पांची माहिती त्वरित मिळवा.',
    aiStatus: 'ऑनलाईन आणि तयार',
    aiGreeting: 'नमस्कार! मी आपला दौंड डिजिटल सहाय्यक आहे. मी आपली काय मदत करू शकतो?',
    aiUpdateMsg: '🇮🇳 अपडेट: Zilla Parishad School Renovation प्रकल्पाचे काम सध्या जोरात सुरू आहे! Modernizing 10 rural schools with digital labs.. आम्ही दौंडच्या प्रगतीसाठी कटिबद्ध आहोत.',
    aiPlaceholder: 'टाइप करा किंवा माईक वापरा...',
    aiAskComplaint: 'तक्रार कशी नोंदवायची?',
    aiAskProjects: 'नुकतेच कोणते प्रकल्प सुरू झाले आहेत?',
    aiAskEmergency: 'आपत्कालीन संपर्क दाखवा',
    liveMapTitle: 'थेट विकास नकाशा',
    liveMapDesc: 'मतदारसंघातील सर्व विकासकामे नकाशावर पाहा.',
    emergencyContactsTitle: 'संपर्क सूची',
    emergencyContactsDesc: 'पोलीस, रुग्णालय, वीज विभागाचे थेट क्रमांक.',
    transparencyTitle: 'पारदर्शकता',
    transparencySub: 'सार्वजनिक निधी आणि प्रगतीचा मागोवा',
    mlaFundTrackerTitle: 'आमदार निधी खर्च माहितीपट्टी (२०२४-२५)',
    roads: 'रस्ते',
    water: 'पाणी',
    education: 'शिक्षण',
    health: 'आरोग्य',
    crore: 'कोटी',
    projects: 'प्रकल्प',
    addProject: 'प्रकल्प जोडा',
    editProject: 'प्रकल्प संपादित करा',
    projectTitle: 'प्रकल्पाचे नाव',
    projectDesc: 'वर्णन',
    estimatedBudget: 'अपेक्षित निधी',
    actualSpent: 'अपेक्षित निधी',
    complete: 'पूर्ण',
    underProcess: 'प्रगतीपथावर',
    incomplete: 'अपूर्ण',
    totalBudget: 'एकूण निधी',
    totalSpent: 'एकूण खर्च',
    totalProjects: 'एकूण प्रकल्प',
    allProjects: 'सर्व प्रकल्प',
    projectAdded: 'प्रकल्प यशस्वीरित्या जोडला गेला',
    projectUpdated: 'प्रकल्प यशस्वीरित्या अद्ययावत केला',
    projectDeleted: 'प्रकल्प यशस्वीरित्या हटवला',
    expectedCompletion: 'अपेक्षित पूर्णता तारीख',
    completionDate: 'पूर्णता तारीख',
    emergencyCall: 'आत्ता कॉल करा',
    police: 'पोलीस स्टेशन',
    ambulance: 'रुग्णवाहिका / रुग्णालय',
    fire: 'अग्निशमन दल',
    electricity: 'वीज महामंडळ',
    tehsildar: 'तहसीलदार कार्यालय',
    comingSoon: 'लवकरच येत आहे',
    citizenRegistration: 'नागरिक नोंदणी',
    createAccountSub: 'तक्रार नोंदवण्यासाठी खाते तयार करा',
    fullName: 'पूर्ण नाव',
    fullNamePlaceholder: 'पूर्ण नाव प्रविष्ट करा',
    selectTalukaOptional: 'तालुका (पर्यायी)',
    register: 'नोंदणी करा',
    registering: 'नोंदणी होत आहे...',
    alreadyHaveAccount: 'आधीच खाते आहे का?',
    loginHere: 'येथे लॉगिन करा',
    citizenLogin: 'नागरिक लॉगिन',
    accessComplaintsSub: 'आपल्या तक्रारी पहा',
    loggingIn: 'लॉगिन होत आहे...',
    dontHaveAccount: 'खाते नाही का?',
    registerHere: 'येथे नोंदणी करा',
    authPersonnelOnly: 'केवळ अधिकृत कर्मचारी',
    marathiAuthSub: 'केवळ अधिकृत कर्मचार्‍यांसाठी',
    aiMessageRBot: 'RBot ला संदेश पाठवा...',
    aiRBotPersona: 'RBot • AI सहाय्यक • आत्ता',
    aiMistakesDisclaimer: 'RBot चुका करू शकतो. महत्वाची माहिती तपासा.',
    aiOnlineReady: 'ऑनलाईन आणि तयार',
    aiTeamHelp: 'संघाची मदत देखील मिळेल',
    complaintIdOrMobile: 'तक्रार क्रमांक किंवा मोबाइल नंबर',
    minSixChars: 'किमान ६ अक्षरे',
    road: 'रस्ता',
    waterDept: 'पाणी',
    electricityDept: 'वीज',
    revenue: 'महसूल',
    police: 'पोलीस',
    health: 'आरोग्य',
    education: 'शिक्षण',
    agri: 'कृषी',
    other: 'इतर',
    maxChars: 'जास्तीत जास्त ५०० अक्षरे',
    photoOptional: 'फोटो (पर्यायी)',
    searching: 'शोधत आहे...',
    pendingStatus: 'प्रलंबित',
    inProgressStatus: 'प्रगतीपथावर',
    resolvedStatus: 'निकाली',
    stepText: 'स्टेप',
    officialPortal: 'अधिकृत पोर्टल',
    digitalIndia: 'डिजिटल इंडिया',
    onlineSupportBadge: '२४/७ ऑनलाईन सपोर्ट',
    quickLinks: 'द्रुत दुवे',
    contact: 'संपर्क',
    followUs: 'आमचे अनुसरण करा',
    rbotGreeting: 'नमस्कार! 👋',
    chatWithSupport: 'RBot सपोर्टशी चॅट करा',
    rbotHome: 'होम',
    rbotMessages: 'संदेश',
    rbotHelp: 'मदत',
    adminLogoutNotice: 'आपल्याला लॉग आउट केले गेले आहे. प्रशासक नागरिक पोर्टल वापरू शकत नाहीत.',
    citizenLogoutNotice: 'हे पोर्टल फक्त प्रशासकीय कर्मचाऱ्यांसाठी आहे.',
    emergencyServices: 'आपत्कालीन सेवा',
    publicUtilities: 'सार्वजनिक सेवा',
    importantNote: 'महत्वाची टीप',
    emergencyDisclaimer: 'हे नंबर फक्त आपत्कालीन आणि अधिकृत वापरासाठी आहेत. कृपया त्यांचा जबाबदारीने वापर करा.',
    officeDaund: 'कार्यालय · दौंड',
    priorityMsg: 'आपल्या समस्यांचे निराकरण आमची प्राथमिकता',
    joinThousands: 'दौंडमधील हजारो नागरिकांमध्ये सामील व्हा जे अधिकृत पोर्टलद्वारे त्यांच्या तक्रारींचे जलद आणि पारदर्शकपणे निराकरण करत आहेत.',
    citizensRegistered: 'नागरिक आधीच नोंदणीकृत',
    mlaTitle: 'आमदार - दौंड मतदारसंघ',
    assemblyName: 'महाराष्ट्र विधानसभा',
    responseRate: 'प्रतिसाद दर',
    howItWorksTitle: 'हे कसे कार्य करते',
    howItWorksSub: 'तुमची तक्रार सोडवण्यासाठी ३ सोप्या पायऱ्या',
    step1Title: 'तक्रार नोंदवा',
    step1Desc: 'तुमच्या तपशीलांसह तक्रार फॉर्म भरा.',
    step2Title: 'क्रमांक मिळवा',
    step2Desc: 'तक्रार ट्रॅक करण्यासाठी एक युनिक क्रमांक मिळवा.',
    step3Title: 'निराकरण पहा',
    step3Desc: 'स्थिती ट्रॅक करा आणि निराकरण झाल्यावर सूचित व्हा.',
    complaintCategories: 'तक्रार श्रेणी',
    categoriesSub: 'आम्ही सर्व सरकारी विभागांमधील तक्रारी हाताळतो',
    liveUpdates: 'थेट अपडेट्स सक्रिय',
    fileNow: 'आत्ता नोंदवा',
    trackStatus: 'स्थिती तपासा',
    recordingNotice: 'सेवा गुणवत्ता सुनिश्चित करण्यासाठी हे चॅट रेकॉर्ड केले जात आहे.',
    helped: 'मदत झाली 👍',
    showMore: 'आणखी दाखवा 👀',
    talkPerson: 'व्यक्तीशी बोला 👤',
    replyNeeded: 'प्रतिसाद आवश्यक',
    adminRemarkPrompt: 'प्रशासकाने टिप्पणी दिली आहे. विनंती केल्यास आपण अधिक फोटो अपलोड करू शकता.',
    complaintGuide: 'तक्रार मार्गदर्शन',
    statusGuide: 'स्थिती मार्गदर्शन',
    automaticSyncNotice: 'आपल्या {n} मोबाइल नंबरवर नोंदवलेल्या सर्व तक्रारी वर आपोआप दाखवल्या जात आहेत.',
    loginBtn: 'लॉगिन',
    signupBtn: 'नोंदणी',
    or: 'किंवा',
    daundVikasMitra: 'दौंड विकास मित्र',
    helloHowHelp: 'नमस्कार! आम्ही तुम्हाला कशी मदत करू शकतो?',
    sendMessageSub: 'आम्हाला संदेश पाठवा',
    chatSupportSub: 'RBot सपोर्टशी चॅट करा',
    suggestedArticles: 'सुचवलेले लेख',
    searchHelpPlaceholder: 'मदत शोधा',
    securityFooter: '🔐 JWT द्वारे सुरक्षित. केवळ अधिकृत कर्मचाऱ्यांसाठी.',
    committedToResolving: 'सार्वजनिक तक्रारींचे जलद आणि पारदर्शकपणे निराकरण करण्यासाठी कटिबद्ध.',
    allRightsReserved: 'सर्व हक्क राखीव.',
    adminPortalOnly: 'हे पोर्टल फक्त प्रशासकीय कर्मचाऱ्यांसाठी आहे.',
    enterPassword: 'तुमचा पासवर्ड प्रविष्ट करा',
    eGovernance: 'ई-प्रशासन',
    permHubTitle: 'सिस्टम परवानग्या मान्य करा',
    permHubSub: 'चांगल्या अनुभवासाठी, कृपया खालील परवानग्या द्या.',
    permLocation: 'लोकेशन (जवळचे विकास प्रकल्प शोधण्यासाठी)',
    permCamera: 'कॅमेरा (तक्रारींचे फोटो अपलोड करण्यासाठी)',
    permMic: 'मायक्रोफोन (AI सह व्हॉइस चॅटसाठी)',
    allowAll: 'सर्व परवानग्या मान्य करा',
    maybeLater: 'नंतर करू',
    allPermsGranted: 'सर्व परवानग्या यशस्वीरित्या मिळाल्या आहेत!',
    permsDeniedMsg: 'काही परवानग्या नाकारल्या गेल्या आहेत. ब्राउझर सेटिंगमध्ये त्या चालू करा.',
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'mr');
  const t = translations[lang];
  const toggle = () => setLang(l => {
    const next = l === 'en' ? 'mr' : 'en';
    localStorage.setItem('lang', next);
    return next;
  });
  return <LangContext.Provider value={{ lang, t, toggle }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
