/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState } from 'react';

const LangContext = createContext(null);

export const translations = {
  en: {
    siteName: 'MLA Public Grievance Portal',
    mlaName: 'MLA Rahul Subhash Kul',
    constituency: 'Daund, Maharashtra',
    welcome: 'Welcome to the MLA Grievance Redressal Portal',
    welcomeSub: 'Your voice matters. Submit your complaints and track their resolution.',
    fileComplaint: 'File a Complaint',
    trackComplaint: 'Track Complaint',
    home: 'Home', complaints: 'Complaints',
    track: 'Track', admin: 'Admin',
    totalComplaints: 'Total Complaints', pending: 'Pending',
    inProgress: 'In Progress', resolved: 'Resolved',
    name: 'Full Name', mobile: 'Mobile Number', village: 'Village',
    taluka: 'Taluka', department: 'Department', description: 'Complaint Description',
    photo: 'Upload Photo (Optional)', submit: 'Submit Complaint',
    complaintId: 'Complaint ID', status: 'Status', remarks: 'Admin Remarks',
    date: 'Date', actions: 'Actions', search: 'Search',
    filterTaluka: 'Filter by Taluka', filterDept: 'Filter by Department',
    exportCSV: 'Export CSV', adminLogin: 'Admin Login',
    password: 'Password', login: 'Login', logout: 'Logout',
    searchPlaceholder: 'Search complaints (ID, Name, Mobile, Village, Description)...',
    noComplaintsFound: 'No complaints found matching your criteria.',
    refresh: 'Refresh',
    prev: 'Prev',
    next: 'Next',
    allTalukas: 'All Talukas',
    allDepartments: 'All Departments',
    allStatuses: 'All Statuses',
    dashboard: 'Dashboard', manageComplaints: 'Manage Complaints',
    analytics: 'Analytics', users: 'Users Management',
    settings: 'Settings',
    statsOverview: 'Overview of all grievances',
    totalComplaintsLabel: 'Total Complaints',
    resolvedLabel: 'Resolved',
    inProgressLabel: 'In Progress',
    resolutionRate: 'Resolution Rate',
    pendingRate: 'Pending Rate',
    rejected: 'Rejected',
    departmentsTitle: 'Departments',
    pendingLabel: 'pending',
    quickActions: 'Quick Actions',
    viewAllComplaints: 'View All Complaints',
    exportData: 'Export Data',
    analyticsTitle: 'Analytics Dashboard',
    resolutionInsights: 'Visual insights into grievance data',
    complaintsByDept: 'Complaints by Department',
    complaintsByTaluka: 'Complaints by Taluka',
    monthlyTrend: 'Monthly Complaint Trend',
    createUserInfo: 'Create New User',
    allUsers: 'All Users',
    createUser: 'Create User',
    saveChanges: 'Save Changes',
    active: 'Active',
    inactive: 'Inactive',
    profileUpdate: 'Update Profile',
    successProfileUpdate: 'Profile updated successfully!',
    privacyError: 'Privacy restricted: You can only search your own mobile number.',
    mobileOwnershipError: 'You must be logged in to search by mobile number.',
    changePassword: 'Change Password (Optional)',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    passwordPlaceholder: 'Leave blank to keep unchanged',
    minChars: 'Min 6 characters',
    roles: {
      super_admin: 'Super Admin',
      taluka_coordinator: 'Taluka Coordinator',
      data_entry_operator: 'Data Entry Operator',
      citizen: 'Citizen'
    },
    noComplaintsTitle: 'No complaints found',
    noComplaintsSub: 'No complaints found for this ID or mobile number.',
    complaintsFoundLabel: 'complaint(s) found',
    filedOn: 'Filed On',
    resolvedOn: 'Resolved On',
    submitted: 'Submitted',
    adminRemarks: 'Admin Remarks',
    adminReplyPhotos: 'Admin Reply Photos',
    citizenReplyPhotos: 'My Reply Photos',
    initialPhoto: 'Initial Uploaded Photo',
    replyMorePhotos: 'Reply / Upload More Photos',
    replyLimitInfo: 'You can upload up to {n} more photos',
    dragDropHint: 'Drag & drop or click to upload',
    fileLimitInfo: 'JPG, PNG, PDF up to 15MB',
    fileLimitInfoSmall: 'JPG, PNG, PDF up to 5MB',
    sendingReply: 'Uploading...',
    sendReply: 'Send Reply',
    fileSelected: '{n} file(s) selected',
    fileSizeError: 'Some files were ignored because they exceed the 5MB limit.',
    atLeastOnePhotoError: 'Please select at least one photo to reply.',
    replySuccess: 'Reply submitted successfully!',
    loginRequired: 'Login Required',
    loginRequiredSub: 'Please log in to register a complaint.',
    goToLogin: 'Go to Login',
    submitComplaintTitle: 'Submit Your Complaint',
    submitComplaintSub: 'Register your issue here',
    namePlaceholder: 'Enter full name',
    mobilePlaceholder: '10-digit mobile number',
    mobileLocked: 'Mobile locked to your login account',
    searchHint: 'e.g. GRV-ABC123-XY or 9876543210',
    villagePlaceholder: 'Enter your village name',
    selectTaluka: '— Select Taluka —',
    descriptionPlaceholder: 'Describe your complaint in detail...',
    submitting: 'Submitting...',
    genuineComplaintWarning: 'By submitting, you agree that this is a genuine complaint.',
    updateSuccess: 'Updated successfully!',
    noChangesError: 'No changes to save.',
    updateError: 'Update failed. Please try again.',
    deleteConfirm: 'Are you sure you want to delete this user?',
    viewMyComplaints: 'View My Complaints',
    successSubmit: 'Complaint submitted successfully!',
    close: 'Close',
    viewDetails: 'View Details',
    details: 'Details',
    citizenUploaded: 'Citizen Uploaded',
    items: 'items',
    total: 'total',
    page: 'Page',
    whatsapp: 'WhatsApp Us',
    darkMode: 'Dark Mode',
    language: 'मराठी',
  },
  mr: {
    siteName: 'आमदार सार्वजनिक तक्रार निवारण पोर्टल',
    mlaName: 'आमदार राहुल सुभाष कुल',
    constituency: 'दौंड, महाराष्ट्र',
    welcome: 'आमदार तक्रार निवारण पोर्टलमध्ये आपले स्वागत आहे',
    welcomeSub: 'आपला आवाज महत्त्वाचा आहे. आपल्या तक्रारी सादर करा आणि त्यांचे निराकरण ट्रॅक करा.',
    fileComplaint: 'तक्रार नोंदवा',
    trackComplaint: 'तक्रार ट्रॅक करा',
    home: 'मुख्यपृष्ठ', complaints: 'तक्रारी',
    track: 'ट्रॅक', admin: 'प्रशासक',
    totalComplaints: 'एकूण तक्रारी', pending: 'प्रलंबित',
    inProgress: 'प्रक्रियेत', resolved: 'निराकृत',
    name: 'पूर्ण नाव', mobile: 'मोबाइल नंबर', village: 'गाव',
    taluka: 'तालुका', department: 'विभाग', description: 'तक्रार तपशील',
    photo: 'फोटो अपलोड करा (पर्यायी)', submit: 'तक्रार सादर करा',
    complaintId: 'तक्रार क्रमांक', status: 'स्थिती', remarks: 'प्रशासक टिप्पणी',
    date: 'तारीख', actions: 'कृती', search: 'शोधा',
    filterTaluka: 'तालुकानुसार फिल्टर', filterDept: 'विभागानुसार फिल्टर',
    exportCSV: 'CSV निर्यात', adminLogin: 'प्रशासक लॉगिन',
    password: 'पासवर्ड', login: 'लॉगिन', logout: 'लॉगआउट',
    searchPlaceholder: 'तक्रारी शोधा (नंबर, नाव, मोबाइल, गाव, तपशील)...',
    noComplaintsFound: 'आपल्या निकषांशी जुळणारी एकही तक्रार आढळली नाही.',
    refresh: 'रिफ्रेश',
    prev: 'मागे',
    next: 'पुढे',
    allTalukas: 'सर्व तालुके',
    allDepartments: 'सर्व विभाग',
    allStatuses: 'सर्व स्थिती',
    dashboard: 'डॅशबोर्ड', manageComplaints: 'तक्रारी व्यवस्थापन',
    analytics: 'विश्लेषण', users: 'वापरकर्ते व्यवस्थापन',
    settings: 'सेटिंग्ज',
    statsOverview: 'तक्रारींचा आढावा',
    totalComplaintsLabel: 'एकूण तक्रारी',
    resolvedLabel: 'निराकृत',
    inProgressLabel: 'प्रक्रियेत',
    resolutionRate: 'निराकरण दर',
    pendingRate: 'प्रलंबित दर',
    rejected: 'नाकारलेले',
    departmentsTitle: 'विभाग',
    pendingLabel: 'प्रलंबित',
    quickActions: 'त्वरित कृती',
    viewAllComplaints: 'सर्व तक्रारी पहा',
    exportData: 'डेटा निर्यात करा',
    analyticsTitle: 'विश्लेषण डॅशबोर्ड',
    resolutionInsights: 'तक्रार निवारण अंतर्दृष्टी',
    complaintsByDept: 'विभागांनुसार तक्रारी',
    complaintsByTaluka: 'तालुक्यांनुसार तक्रारी',
    monthlyTrend: 'मासिक तक्रार कल',
    createUserInfo: 'नवीन वापरकर्ता तयार करा',
    allUsers: 'सर्व वापरकर्ते',
    createUser: 'वापरकर्ता तयार करा',
    saveChanges: 'बदल जतन करा',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    profileUpdate: 'प्रोफाइल अपडेट करा',
    successProfileUpdate: 'प्रोफाइल यशस्वीरित्या अपडेट केली!',
    privacyError: 'गोपनीयता प्रतिबंधित: आपण फक्त आपला स्वतःचा मोबाइल नंबर शोधू शकता.',
    mobileOwnershipError: 'मोबाइल नंबरद्वारे शोधण्यासाठी कृपया लॉग इन करा.',
    changePassword: 'पासवर्ड बदला (पर्यायी)',
    currentPassword: 'चालू पासवर्ड',
    newPassword: 'नवीन पासवर्ड',
    passwordPlaceholder: 'बदल न करण्यासाठी रिक्त ठेवा',
    minChars: 'किमान ६ वर्ण',
    roles: {
      super_admin: 'सुपर ॲडमिन',
      taluka_coordinator: 'तालुका समन्वयक',
      data_entry_operator: 'डेटा एंट्री ऑपरेटर',
      citizen: 'नागरिक'
    },
    noComplaintsTitle: 'तक्रार आढळली नाही',
    noComplaintsSub: 'या आयडी किंवा मोबाइल नंबरसाठी कोणतीही तक्रार आढळली नाही.',
    complaintsFoundLabel: 'तक्रारी आढळल्या',
    filedOn: 'दाखल तारीख',
    resolvedOn: 'निकाली तारीख',
    submitted: 'सादर केली',
    adminRemarks: 'प्रशासकीय शेरा',
    adminReplyPhotos: 'प्रशासक फोटो',
    citizenReplyPhotos: 'माझे फोटो',
    initialPhoto: 'सुरुवातीचा फोटो',
    replyMorePhotos: 'उत्तर द्या / अधिक फोटो अपलोड करा',
    replyLimitInfo: 'तुम्ही आणखी {n} फोटो अपलोड करू शकता',
    dragDropHint: 'फोटो येथे ओढा किंवा अपलोड करण्यासाठी क्लिक करा',
    fileLimitInfo: 'JPG, PNG, PDF १५MB पर्यंत',
    fileLimitInfoSmall: 'JPG, PNG, PDF ५MB पर्यंत',
    sendingReply: 'अपलोड होत आहे...',
    sendReply: 'उत्तर पाठवा',
    fileSelected: '{n} फाइल निवडली',
    fileSizeError: 'काही फाइल्स ५MB पेक्षा जास्त असल्यामुळे वगळल्या गेल्या.',
    atLeastOnePhotoError: 'कृपया प्रतिसादासाठी किमान एक फोटो निवडा.',
    replySuccess: 'उत्तर यशस्वीरित्या पाठवले!',
    loginRequired: 'लॉगिन आवश्यक',
    loginRequiredSub: 'तक्रार नोंदवण्यासाठी कृपया आधी लॉग इन करा.',
    goToLogin: 'लॉगिन करा',
    submitComplaintTitle: 'तुमची तक्रार सादर करा',
    submitComplaintSub: 'तुमची समस्या येथे नोंदवा',
    namePlaceholder: 'पूर्ण नाव टाका',
    mobilePlaceholder: '१०-अंकी मोबाइल नंबर',
    mobileLocked: 'मोबाइल नंबर बदलता येणार नाही',
    searchHint: 'उदा. GRV-ABC123-XY किंवा 9876543210',
    villagePlaceholder: 'गावाचे नाव टाका',
    selectTaluka: '— तालुका निवडा —',
    descriptionPlaceholder: 'तक्रारीचा सविस्तर तपशील द्या...',
    submitting: 'सादर होत आहे...',
    genuineComplaintWarning: 'सादर करून, आपण सहमत आहात की ही खरी तक्रार आहे.',
    updateSuccess: 'यशस्वीरित्या अपडेट केले!',
    noChangesError: 'बदल करण्यासाठी काहीही नाही.',
    updateError: 'अपडेट अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    deleteConfirm: 'आपल्याला खात्री आहे की आपण हा वापरकर्ता हटवू इच्छिता?',
    viewMyComplaints: 'माझ्या तक्रारी पहा',
    successSubmit: 'तक्रार यशस्वीरित्या नोंदवली गेली!',
    close: 'बंद करा',
    viewDetails: 'तपशील पहा',
    details: 'तपशील',
    citizenUploaded: 'नागरिकाने अपलोड केलेले',
    items: 'तक्रारी',
    total: 'एकूण',
    page: 'पृष्ठ',
    whatsapp: 'व्हाट्सअॅप करा',
    darkMode: 'डार्क मोड',
    language: 'English',
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');
  const t = translations[lang];
  const toggle = () => setLang(l => {
    const next = l === 'en' ? 'mr' : 'en';
    localStorage.setItem('lang', next);
    return next;
  });
  return <LangContext.Provider value={{ lang, t, toggle }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
